apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmap.yml
  - pvcs.yml
  - elasticsearch.yml
  - kibana.yml
  - apm-server.yml
  - otel-collector.yml
  - ingress.yml
