apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-platform-ingress
  namespace: redis-platform
  labels:
    app.kubernetes.io/part-of: redis-platform
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    # Redis Insight â€“ accessible at http://redis-insight.127.0.0.1.sslip.io:8080
    - host: redis-insight.127.0.0.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-insight
                port:
                  number: 5540
