apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb
  namespace: azure-platform
  labels:
    app: cosmosdb
    app.kubernetes.io/part-of: azure-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cosmosdb
    spec:
      containers:
        - name: cosmosdb
          image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
          tty: true
          ports:
            - containerPort: 8081
              name: service
            - containerPort: 1234
              name: explorer
          env:
            - name: PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: azure-platform-config
                  key: PROTOCOL
            - name: EXPLORER_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: azure-platform-config
                  key: EXPLORER_PROTOCOL
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: azure-platform-config
                  key: DATA_PATH
            - name: AZURE_COSMOS_EMULATOR_ENABLE_DATA_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: azure-platform-config
                  key: AZURE_COSMOS_EMULATOR_ENABLE_DATA_HTTPS
            - name: AZURE_COSMOS_EMULATOR_PARTITION_COUNT
              valueFrom:
                configMapKeyRef:
                  name: azure-platform-config
                  key: AZURE_COSMOS_EMULATOR_PARTITION_COUNT
            - name: AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE
              valueFrom:
                configMapKeyRef:
                  name: azure-platform-config
                  key: AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE
          volumeMounts:
            - name: cosmosdb-data
              mountPath: /data
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "3"
              memory: "6Gi"
      volumes:
        - name: cosmosdb-data
          persistentVolumeClaim:
            claimName: cosmosdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: cosmosdb
  namespace: azure-platform
  labels:
    app: cosmosdb
    app.kubernetes.io/part-of: azure-platform
spec:
  type: ClusterIP
  selector:
    app: cosmosdb
  ports:
    - name: service
      port: 8081
      targetPort: 8081
    - name: explorer
      port: 1234
      targetPort: 1234
