apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-1
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-2
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-3
  namespace: kafka-platform
  labels:
    app.kubernetes.io/part-of: kafka-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
