apiVersion: v1
kind: Secret
metadata:
  name: postgres-platform-secrets
  namespace: postgres-platform
  labels:
    app.kubernetes.io/part-of: postgres-platform
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "postgres"
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "password"
