name: kafka-stack

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.7.6
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    volumes:
      - vol_zookeeper_data:/var/lib/zookeeper/data
      - vol_zookeeper_txn:/var/lib/zookeeper/log
    networks:
      app-internal-network:

  kafka-broker-1:
    container_name: kafka-broker-1
    image: confluentinc/cp-kafka:7.7.6
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker-1:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -z localhost 19092 || exit -1
      interval: 30s
      timeout: 10s
      retries: 25
    restart: unless-stopped
    volumes:
      - vol_kafka:/var/lib/kafka/data
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      app-internal-network:

  schema-registry:
    hostname: schema-registry
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:7.7.6
    ports:
      - '8988:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker-1:19092'
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
    networks:
      app-internal-network:

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:19092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_BROKERCONNECT: kafka-broker-1:19092
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka-broker-1:
        condition: service_healthy
    networks:
      app-internal-network:


networks:
  app-internal-network:
    external: true
    name: app-internal-network

volumes:
  vol_zookeeper_data:
  vol_zookeeper_txn:
  vol_kafka: